name: "[Test] Desktop App"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test-desktop-app:
    name: "Ledger Live Desktop Tests"
    env:
      NODE_OPTIONS: "--max-old-space-size=7168"
      INSTRUMENT_BUILD: true
      FORCE_COLOR: 3
      CI_OS: ${{ matrix.os }}
      # DEBUG: "pw:browser*"
      # DEBUG_LOGS: 1
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-latest
          # - macos-latest
          - windows-latest
        ref:
          - deb90cd165e79696b1418d17c602e165cc546f9f
          - 177fe191fd407d6d8b2c789b06709ceb85e997ed
          - 7d8491996a51f7868994f9f16a0cb54133af06de
          - 42051cd1dcf34785d3643a42ec7fd353d1cc5c9f
          - 8cc0ada29963f2d07311ecdcf6d4fb1280c14091

    runs-on: ${{ matrix.os }}
    steps:
      - name: format os name
        id: os
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            if ("${{ matrix.os }}" === "ubuntu-latest") {
              return "linux"
            } else if ("${{ matrix.os }}" === "macos-latest") {
              return "macos"
            } else if ("${{ matrix.os }}" === "windows-latest") {
              return "windows"
            }
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.ref }}
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Bump npm to latest
        run: npm i -g npm
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: "yolo"
      - name: Install dependencies
        run: pnpm i --filter="ledger-live-desktop..." --filter="ledger-live" --frozen-lockfile --unsafe-perm
      - name: Install playwright dependencies
        run: npx @playwright/test install-deps
      - name: Build dependencies
        run: pnpm turbo run ledger-live-desktop#build:testing --api="http://127.0.0.1:9080" --token="yolo" --team="foo"
      - name: Run unit tests [Linux]
        if: matrix.os == 'ubuntu-latest'
        run: pnpm desktop test:jest
      - name: Run playwright tests [Linux => xvfb-run]
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm desktop test:playwright
        shell: bash
      - name: Run playwright tests
        if: matrix.os != 'ubuntu-latest'
        run: pnpm desktop test:playwright
        shell: bash
